# Generated by Django 2.0.7 on 2018-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FilePathField(path='/images')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('highlights', models.TextField()),
                ('category', models.CharField(max_length=15)),
                ('days', models.IntegerField()),
            ],
        ),
    ]
