# Generated by Django 2.0.7 on 2018-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='photo',
            field=models.FilePathField(path='/holiday/images'),
        ),
    ]
