# Generated by Django 2.0.7 on 2018-08-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_auto_20180819_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='photo',
            field=models.FilePathField(path='/home/hemal//Workspaces/Python Workspace/django/makemyholiday/holiday/static/holiday/images', recursive=True),
        ),
    ]
