# Generated by Django 2.0.7 on 2018-08-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0006_auto_20180819_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
