# Generated by Django 2.0.7 on 2018-08-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0007_auto_20180819_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='name',
            field=models.CharField(default='place', max_length=100),
            preserve_default=False,
        ),
    ]
