# Generated by Django 2.0.7 on 2018-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0009_flight_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='photo',
            field=models.CharField(default='img name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.CharField(default='img', max_length=100),
            preserve_default=False,
        ),
    ]
